on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18.x

    - run: yarn install

# We don't have any tests yet.
#    - run: xvfb-run -a npm test

    - name: Publish
      if: success()
      run: yarn run deploy
      env:
        VSCE_PAT: ${{ secrets.VSCE_PAT }}
